name = "promptduel-worker"
main = "src/index.ts"
compatibility_date = "2024-05-30"

[[kv_namespaces]]
binding = "DUELS_KV"
id = "place_holder_kv_namespace_id_to_be_replaced_in_prod"

[triggers]
crons = ["0 0 * * *"]

